### ISSUE TITLE
Gnome 40 support

### ISSUE THREAD

**Issue by ReillyBrogan** [maoschanz/notes-extension-gnome#67]
Extension seems functional if metadata.json is manually modified. Settings don't work however as they need to be ported to GTK4.

**Comment by ReillyBrogan** [comment]
I don't know if you've seen it already, but just in case you haven't it looks like the Gnome devs put out a pretty guide for porting to GNOME 40 [here](https://gjs.guide/extensions/upgrading/gnome-shell-40.html).

**Comment by nosklo** [comment]
I have forced the extension to work in gnome 41, including the settings, by dropping support for old versions. I did it as fast as possible because my peers have come to depend on it. The branch is [here](https://github.com/nosklo/notes-extension-gnome/tree/reborn) if someone finds it useful. I can open a pull request if you want to drop old gnome support too.
