### ISSUE TITLE
Notes are off-screen when switching layouts

### ISSUE THREAD

**Issue by floe** [maoschanz/notes-extension-gnome#71]
When I undock my laptop, the notes are no longer visible because they are now "off-screen". Toggling them also doesn't help. Might be an idea to include a "reset positions" option in the menu icon? Or perhaps store positions based on screen configuration, although I have no idea how hard or easy that might be.

**Comment by floe** [comment]
After browsing the code a bit, I noticed there's a `bring-back` signal that does more or less exactly what I want, but how would I trigger this from outside?

**Comment by maoschanz** [comment]
there is a button somewhere in the extension's preferences

**Comment by floe** [comment]
> there is a button somewhere in the extension's preferences

Yes, I know, _but_ - you cannot access the preferences if you don't see the notes, because the only way to get to the preferences is from the context menu of a note?

**Comment by maoschanz** [comment]
Like any other extension's preferences, it's accessible at least from extensions.gnome.org, from the "GNOME Tweaks" app, and from the "GNOME Extensions" app. Maybe from "GNOME Software" too, depending on your version of GNOME

**Comment by floe** [comment]
Okay, that's a workaround, thanks (would still prefer to have this as a hotkey, or automatically on unplug, though)

**Comment by maoschanz** [comment]
i assumed there were 2 main possible cases:

- regularly plugging/unplugging a secondary monitor (*for example a laptop with a desktop display or not depending on the company's fucking working-from-home covid policies*). I often plug/unplug it from the laptop, and i'm happy the notes are still on my second monitor when it is back, instead of moving each time: this wouldn't be possible if it was automatic.

- not regularly doing that, so the missing notes are a one-time accident, and the feature doesn't have to be prominently accessible at any moment

i can imagine other weird cases that the extension don't support, such as a secondary monitor defined as the "primary" one in the display settings, and positioned to the left of the actual primary one? that would break things i guess, but i have no intention breaking my own configuration to develop a fix for this absurd situation, sorry: if this is your case i suggest to not move your notes too far from the monitor where the icon is
